# Generated by Django 4.2 on 2024-05-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='credit_card',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trader',
            name='is_auth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trader',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
